// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: bbd2664dd82192fb5209c2bd31dc981836563d13e20cc856f257537f3f022bde

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "planingo-theme";

export const themeNames: ThemeName[] = ["planingo-theme"];

export type KcEnvName = "ENABLE_THEME_TOGGLE";

export const kcEnvNames: KcEnvName[] = ["ENABLE_THEME_TOGGLE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ENABLE_THEME_TOGGLE: "true"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
